# Consul API Gateway — Nomad job.
#
# The Consul API Gateway has NO native Nomad jobspec integration:
#   connect { gateway { api {} } }  ← NOT valid (causes "Blocks of type 'api' are not expected here")
# Nomad's gateway stanza only supports ingress, terminating, and mesh.
#
# Correct approach: two-task job using 'consul connect envoy -gateway api':
#   1. setup (prestart): Consul image registers the gateway and generates Envoy bootstrap config.
#   2. api (main):       Envoy image starts with the generated bootstrap config.
#
# Reference: https://developer.hashicorp.com/nomad/tutorials/integrate-consul/deploy-api-gateway-on-nomad
#
# Prerequisites:
#   - CNI plugins installed on all nodes (done by setup_nomad_aws_ami.sh)
#   - Consul API Gateway config entry written (infrastructure/api-gateway/gateway.consul.hcl)
#   - Routes written (infrastructure/api-gateway/routes/*.consul.hcl)
#   - This POC uses plain HTTP Consul (no TLS, no ACL) → no cert/token setup required.
#     For a production setup with ACL enabled, Nomad Workload Identity and a Consul
#     ACL binding rule for builtin/api-gateway would be needed.
#
# Run: nomad job run infrastructure/api-gateway/job.nomad.hcl

job "api-gateway" {
  datacenters = ["dc1"]

  # system type: one allocation per node for HA (gateway runs on all 3 nodes)
  type = "system"

  group "gateway" {
    network {
      # bridge mode required for Consul Connect CNI
      mode = "bridge"

      # HTTP listener — all HTTP services share this port (routed by Host header via api-gateway)
      port "http" {
        static = 8080
        to     = 8080
      }

      # TCP listener — one port per HTTPS-native service (no Host header routing at TCP level)
      # https-service: 8082. Add a new port + listener in gateway.consul.hcl for each HTTPS service.
      port "https-service" {
        static = 8082
        to     = 8082
      }
    }

    # setup: registers the gateway with Consul and writes the Envoy bootstrap config to
    # NOMAD_ALLOC_DIR so the 'api' task can read it on startup.
    task "setup" {
      driver = "docker"

      lifecycle {
        hook    = "prestart"
        sidecar = false
      }

      config {
        image   = "hashicorp/consul:1.22.3"
        command = "/bin/sh"
        args = [
          "-c",
          "consul connect envoy -gateway api -register -deregister-after-critical 10s -service ${NOMAD_JOB_NAME} -admin-bind 0.0.0.0:19000 -ignore-envoy-compatibility -bootstrap > ${NOMAD_ALLOC_DIR}/envoy_bootstrap.json"
        ]
      }

      env {
        # Node IP (not 127.0.0.1) is required: bridge networking containers cannot
        # reach the host loopback. attr.unique.network.ip-address is the node's primary IP.
        CONSUL_HTTP_ADDR = "http://${attr.unique.network.ip-address}:8500"
        CONSUL_GRPC_ADDR = "${attr.unique.network.ip-address}:8502"
      }
    }

    # api: runs the Envoy proxy using the bootstrap config generated by 'setup'.
    # Envoy 1.29.x is compatible with Consul 1.22.x.
    task "api" {
      driver = "docker"

      config {
        image = "envoyproxy/envoy:v1.29.9"
        args = [
          "--config-path", "${NOMAD_ALLOC_DIR}/envoy_bootstrap.json",
          "--log-level", "info",
          "--concurrency", "2",
          "--disable-hot-restart"
        ]
      }
    }
  }
}
